site_name: Netspresso Documents
site_url: https://cbpark-nota.github.io/cbpark-nota/
theme:
  name: material
  favicon: assets/images/favicon.png
  features:
    - navigation.path
    - navigation.indexes
    - navigation.top
    - navigation.instant
    - navigation.instant.progress

nav:
  - Home: index.md
  - LaunchX: launchx.md
  - Compatibility range of conversion: launchx/compatibility_range_of_conversion.md
  - Supported JetPack-ONNX version: launchx/supported_jetpack_onnx_version.md