site_name: Netspresso Documents
site_url: https://cbpark-nota.github.io/cbpark-nota/
theme:
  name: material
  favicon: assets/images/favicon.png
  features:
    # - navigation.path
    - navigation.indexes
    - navigation.top
    # - navigation.instant
    # - navigation.instant.progress

nav:
  - Home: index.md
  - LaunchX: en/launchx.md
  - Compatibility range of conversion: 
    - en/launchx/compatibility_range_of_conversion.md
    - Supported JetPack-ONNX version: en/launchx/supported_jetpack_onnx_version.md
  - Compatibility range of benchmark: en/launchx/compatibility_range_of_benchmark.md
  - INT8 quantization with LaunchX: en/launchx/int8_quantization_with_launchx.md
  - LaunchX: ko/launchx.md
  - 변환 호환성 범위:
    - ko/launchx/compatibility_range_of_conversion.md
    - 지원되는 JetPack-ONNX version: ko/launchx/supported_jetpack_onnx_version.md
  - 벤치마크 호환성 범위: ko/launchx/compatibility_range_of_benchmark.md
  - LaunchX 를 통한 INT8 양자화: ko/launchx/int8_quantization_with_launchx.md

# extra:
#   alternate:
#     - name: English
#       link: en/launchx/
#       lang: en
#     - name: Korean
#       link: ko/
#       lang: ko