site_name: Netspresso Documents
site_url: https://cbpark-nota.github.io/cbpark-nota/
theme:
  name: material
  favicon: assets/images/favicon.png

  nav:
  - Home: index.md
  - LaunchX:
    - LaunchX: launchx/launchx.md
      - Compatibility range of conversion: launchx/compatibility_range_of_conversion