Models
------------

We provide optimized models through NetsPresso. You can immediately utilize these AI models after converting them.

- Utilize a variety of computer vision task models for free.
- You can download converted models.
- You can request customization for a fine-tuned model that is tailored to your project environment.

.. toctree::
   :maxdepth: 2

Convert
-------------
Simplify the process of framework conversion.

.. image:: source/_static/launchx_convert.png

- Easy and efficient model conversion.
- Eliminate trial and error with automated conversion.
- Quickly set up the deployment of models on target devices.

.. toctree::
   :maxdepth: 2